Repository kookmin-sw/capstone-2023-40, pull requests merged in 2023-03, with the labels that each got.

#7 feat: development database and package setup
  api/build.gradle
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application.properties
  api/src/main/resources/application.yml
Labels: feature

#8 chore: install eslint(airbnb) & prettier
  web/.eslintrc.js
  web/.prettierrc
  web/package-lock.json
  web/package.json
  web/tsconfig.json
Labels: feature

#9 chore: added necessary package
  api/src/main/java/com/thesurvey/api/controller/.gitkeep
  api/src/main/java/com/thesurvey/api/domain/.gitkeep
  api/src/main/java/com/thesurvey/api/dto/.gitkeep
  api/src/main/java/com/thesurvey/api/repository/.gitkeep
  api/src/main/java/com/thesurvey/api/service/.gitkeep
Labels: feature

#14 feat: set page routing and add basic pages
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/index.tsx
  web/src/routes/LoginPage/index.tsx
  web/src/routes/MainPage/index.tsx
  web/src/routes/MyPages/AuthListPage/index.tsx
  web/src/routes/MyPages/ProfilePage/index.tsx
  web/src/routes/MyPages/SurveyResPage/index.tsx
  web/src/routes/NotFound.tsx
  web/src/routes/RegisterPage/index.tsx
  web/src/routes/SurveyPages/SurveyFormPage/index.tsx
  web/src/routes/SurveyPages/SurveyListPage/index.tsx
  web/src/routes/SurveyPages/SurveyLoginReqPage/index.tsx
  web/src/routes/SurveyPages/SurveyPage/index.tsx
Labels: feature

#16 Revert "feat: set page routing and add basic pages"
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/index.tsx
  web/src/routes/LoginPage/index.tsx
  web/src/routes/MainPage/index.tsx
  web/src/routes/MyPages/AuthListPage/index.tsx
  web/src/routes/MyPages/ProfilePage/index.tsx
  web/src/routes/MyPages/SurveyResPage/index.tsx
  web/src/routes/NotFound.tsx
  web/src/routes/RegisterPage/index.tsx
  web/src/routes/SurveyPages/SurveyFormPage/index.tsx
  web/src/routes/SurveyPages/SurveyListPage/index.tsx
  web/src/routes/SurveyPages/SurveyLoginReqPage/index.tsx
  web/src/routes/SurveyPages/SurveyPage/index.tsx
Labels: fix

#17 feat: set page routing and add basic pages
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/index.tsx
  web/src/routes/LoginPage.tsx
  web/src/routes/MainPage.tsx
  web/src/routes/MyPages/AuthListPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/routes/NotFound.tsx
  web/src/routes/RegisterPage.tsx
  web/src/routes/SurveyPages/SurveyFormPage.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyLoginRequiredPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
Labels: feature

#18 chore: added logo assets
  web/public/favicon.ico
  web/public/index.html
  web/public/logo192.png
  web/public/logo256.webp
  web/public/logo512.png
  web/public/manifest.json
  web/src/assets/logo-icon.svg
  web/src/assets/logo.svg
  web/src/assets/logo.webp
  web/src/logo.svg
Labels: feature

#23 feat: formatter for import order
  .git-blame-ignore-revs
  web/.eslintrc.js
  web/.prettierrc
  web/package-lock.json
  web/package.json
  web/src/App.test.tsx
  web/src/App.tsx
  web/src/index.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
Labels: feature

#21 feat: add header and main page
  .git-blame-ignore-revs
  web/.eslintrc.js
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/App.css
  web/src/App.tsx
  web/src/assets/logo-dark.svg
  web/src/assets/logo-light.svg
  web/src/assets/main-page.webp
  web/src/components/GlobalStyle.tsx
  web/src/components/Header.tsx
  web/src/hooks/useTheme.ts
  web/src/index.css
  web/src/routes/MainPage.tsx
  web/src/themes/darkTheme.ts
  web/src/themes/index.ts
  web/src/themes/lightTheme.ts
  web/src/types/styled.d.ts
Labels: feature

#27 feat: Added gradle.yml for springboot CI workflow
  .github/workflows/gradle.yml
Labels: feature

#24 #24 feat: add login register page design
  web/.eslintrc.js
  web/package.json
  web/src/components/Header.tsx
  web/src/routes/LoginPage.tsx
  web/src/routes/MainPage.tsx
  web/src/routes/RegisterPage.tsx
  web/src/themes/darkTheme.ts
  web/src/themes/lightTheme.ts
  web/src/types/styled.d.ts
Labels: feature, revision

#29 #29 Feature/compared branch login regist & Theme Toggle icon
  web/.eslintrc.js
  web/src/assets/svg/logo-dark.svg
  web/src/assets/svg/logo-icon.svg
  web/src/assets/svg/logo-light.svg
  web/src/assets/svg/moon.svg
  web/src/assets/svg/sun.svg
  web/src/components/Header.tsx
  web/src/components/ThemeToggle.tsx
  web/src/routes/LoginPage.tsx
  web/src/routes/RegisterPage.tsx
Labels: feature

#28 Feat: add progressbar while page loading
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/index.tsx
Labels: feature

#37 Feat: add survey list page with mock api
  web/package-lock.json
  web/package.json
  web/src/api/axios.ts
  web/src/api/request.ts
  web/src/routes/SurveyPages/SurveyListPage.tsx
Labels: feature

#38 #33 Feature/themetoggle icon & user regist flow
  web/.eslintrc.js
  web/src/assets/svg/Penceil.svg
  web/src/assets/svg/logo-dark.svg
  web/src/assets/svg/logo-icon.svg
  web/src/assets/svg/logo-light.svg
  web/src/components/Header.tsx
  web/src/components/RegistCheck.tsx
  web/src/routes/LoginPage.tsx
  web/src/routes/MainPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/RegisterPage.tsx
Labels: feature

#41 feat: additional domain change
  api/build.gradle
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/domain/BaseTimeEntity.java
  api/src/main/java/com/thesurvey/api/domain/Role.java
  api/src/main/java/com/thesurvey/api/domain/Survey.java
  api/src/main/java/com/thesurvey/api/domain/User.java
  api/src/main/java/com/thesurvey/api/dto/SurveyDto.java
  api/src/main/java/com/thesurvey/api/dto/UserDto.java
  api/src/main/java/com/thesurvey/api/dto/UserInfoDto.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/main/resources/application-dev.yml
Labels: feature, revision

#45 refactor: modified domains for JPA query tuning
  api/src/main/java/com/thesurvey/api/domain/AnsweredQuestion.java
  api/src/main/java/com/thesurvey/api/domain/AnsweredQuestionId.java
  api/src/main/java/com/thesurvey/api/domain/BaseTimeEntity.java
  api/src/main/java/com/thesurvey/api/domain/Participation.java
  api/src/main/java/com/thesurvey/api/domain/ParticipationId.java
  api/src/main/java/com/thesurvey/api/domain/Question.java
  api/src/main/java/com/thesurvey/api/domain/QuestionBank.java
  api/src/main/java/com/thesurvey/api/domain/QuestionId.java
  api/src/main/java/com/thesurvey/api/domain/Survey.java
  api/src/main/java/com/thesurvey/api/domain/User.java
Labels: revision

#46 feat: add exception handler
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/exception/NotFoundException.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
Labels: feature

#47 refactor: util class for numbers
  web/.eslintrc.js
  web/src/components/Pagination.tsx
  web/src/components/Skeleton/SurveyListSkeleton.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/utils/NumberUtils.ts
Labels: revision

#48 fix: set exception to global exception handler
  api/src/main/java/com/thesurvey/api/exception/ExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/resources/application-dev.yml
Labels: fix

#50 feat: session authentication
  .github/workflows/gradle.yml
  api/src/main/java/com/thesurvey/api/config/ApplicationConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SessionFilter.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/domain/User.java
  api/src/main/java/com/thesurvey/api/dto/UserInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/exception/ExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/repository/UserRepository.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/main/resources/application-dev.yml
  api/src/test/java/com/thesurvey/api/service/UserServiceTest.java
Labels: feature

#52 fix: refactor and minor fixes
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/test/java/com/thesurvey/api/service/UserServiceTest.java
Labels: fix

#54 feat: icon toggle button & 404 page
  web/.eslintrc.js
  web/src/assets/darkmode.webp
  web/src/assets/lightmode.webp
  web/src/assets/not-found.webp
  web/src/assets/svg/driver-license-icon.svg
  web/src/assets/svg/error-icon.svg
  web/src/assets/svg/favicon.svg
  web/src/assets/svg/google-icon.svg
  web/src/assets/svg/id-icon.svg
  web/src/assets/svg/index.ts
  web/src/assets/svg/info-icon.svg
  web/src/assets/svg/kakao-icon.svg
  web/src/assets/svg/mobile-phone-icon.svg
  web/src/assets/svg/naver-icon.svg
  web/src/assets/svg/shortcut-icon.svg
  web/src/assets/svg/warn-icon.svg
  web/src/assets/svg/webmail-icon.svg
  web/src/components/AlertModal.tsx
  web/src/components/Header.tsx
  web/src/components/Skeleton/SurveyListSkeleton.tsx
  web/src/routes/NotFound.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyLoginRequiredPage.tsx
  web/src/types/enums.ts
Labels: feature

#60 feat: add user-api (WIP)
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SessionFilter.java
  api/src/main/java/com/thesurvey/api/controller/AuthenticationController.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/test/java/com/thesurvey/api/service/UserServiceTest.java
Labels: feature, revision

#63 Feat: survey page for participants
  web/src/api/request.ts
  web/src/components/Modal/SurveyPageResultModal.tsx
  web/src/components/Skeleton/SurveyPageSkeleton.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
Labels: feature

#66 docs: add swagger for controllers
  api/build.gradle
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SwaggerConfig.java
  api/src/main/java/com/thesurvey/api/controller/AuthenticationController.java
  api/src/main/java/com/thesurvey/api/controller/CustomController.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/dto/request/UserLoginRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/resources/application-dev.yml
Labels: documentation, feature

#69 refactor: base api
  api/src/main/java/com/thesurvey/api/ApiApplication.java
  api/src/main/java/com/thesurvey/api/domain/BaseTimeEntity.java
  api/src/main/java/com/thesurvey/api/repository/AnsweredQuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/ParticipationRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionOptionRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/repository/UserRepository.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/ParticipationService.java
  api/src/main/java/com/thesurvey/api/service/QuestionOptionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/ParticipationMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: fix

#71 feat: add base test code
  web/package-lock.json
  web/package.json
  web/src/App.test.tsx
  web/src/__tests__/MainPage.test.tsx
  web/src/routes/MainPage.tsx
  web/src/setupTests.ts
Labels: feature

#73 Feature: refactoring
  api/src/main/java/com/thesurvey/api/controller/AuthenticationController.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/dto/AnsweredInfoQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/AnsweredQuestionInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/AnsweredQuestionResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionBankResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionOptionResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserResponseDto.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionOptionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/test/java/com/thesurvey/api/service/UserServiceTest.java
Labels: feature

#74 fix: add ordering of survey list response and question options
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/domain/Participation.java
  api/src/main/java/com/thesurvey/api/domain/QuestionBank.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionBankResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserResponseDto.java
  api/src/main/java/com/thesurvey/api/repository/QuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature, fix

#76 Feature: convert requested empty list or string data to null
  .github/workflows/gradle.yml
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionOptionMapper.java
Labels: feature, revision
