Repository kookmin-sw/capstone-2023-40, pull requests merged in 2023-02, with the labels that each got.

#3 base-project
  web/.gitignore
  web/README.md
  web/package-lock.json
  web/package.json
  web/public/favicon.ico
  web/public/index.html
  web/public/logo192.png
  web/public/logo512.png
  web/public/manifest.json
  web/public/robots.txt
  web/src/App.css
  web/src/App.test.tsx
  web/src/App.tsx
  web/src/index.css
  web/src/index.tsx
  web/src/logo.svg
  web/src/react-app-env.d.ts
  web/src/reportWebVitals.ts
  web/src/setupTests.ts
  web/tsconfig.json
Labels: feature, good first issue

#4 fix: uncomment files from gitignore
  .gitignore
Labels: fix

#5 fix: gitignore path
  .gitignore
  api/.gitignore
Labels: fix

#6 feat: added codestyleconfig file
  api/.idea/codeStyles/codeStyleConfig.xml
  api/idea/KMU_CAPSTONE_TEAM_40_CODE_STYLE_CONFIG.xml
Labels: feature
