Repository kookmin-sw/capstone-2023-40, pull requests merged in 2023-05, with the labels that each got.

#127 feat: integrated user authentication API
  web/src/App.tsx
  web/src/__tests__/MainPage.test.tsx
  web/src/api/axios.ts
  web/src/api/request.ts
  web/src/components/Button/Buttons.ts
  web/src/components/Button/ImageButtons.ts
  web/src/components/Header.tsx
  web/src/components/InputContainer.tsx
  web/src/components/LoginForm.tsx
  web/src/components/Modal/AlertModal.tsx
  web/src/components/Modal/ConfirmModal.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/Modal/SurveyPageResultModal.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/RegisterForm.tsx
  web/src/components/SurveyForm/OptionList.tsx
  web/src/components/SurveyForm/QuestionForm.tsx
  web/src/components/SurveyForm/SurveyDataForm.tsx
  web/src/contexts/AuthContext.ts
  web/src/contexts/ProtectedRoute.tsx
  web/src/hooks/useOnClickOutside.ts
  web/src/reducers/auth.ts
  web/src/reducers/form.ts
  web/src/reducers/header.ts
  web/src/reducers/index.ts
  web/src/reducers/profile.ts
  web/src/reducers/survey.ts
  web/src/reducers/user.ts
  web/src/routes/LoginPage.tsx
  web/src/routes/MainPage.tsx
  web/src/routes/MyPages/AuthListPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/NotFound.tsx
  web/src/routes/SurveyPages/SurveyFormPage.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
  web/src/types/context.ts
  web/src/types/profile.ts
  web/src/types/registerForm.ts
  web/src/types/request/Authentication.ts
  web/src/types/request/index.ts
  web/src/types/response/BaseTime.ts
  web/src/types/response/Survey.ts
  web/src/types/surveyAuth.ts
  web/src/types/user.ts
Labels: feature, fix

#132 build: dockerizing service applications
  .github/workflows/gradle.yml
  api/.dockerignore
  api/Dockerfile
  api/src/main/resources/application-local.yml
  api/src/main/resources/application.yml
  docker-compose.yml
  web/Dockerfile
  web/package-lock.json
  web/package.json
  web/src/.dockerignore
  web/src/api/axios.ts
Labels: feature, fix

#136 refactor: minor fixes
  api/Dockerfile
  api/src/main/java/com/thesurvey/api/dto/response/question/QuestionBankAnswerDto.java
  api/src/main/java/com/thesurvey/api/dto/response/question/QuestionOptionAnswerDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/resources/application.yml
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
  web/.dockerignore
Labels: fix, refactor

#139 fix: 개별 설문조사 조회 API에서 json 데이터 중`questions`가 항상 null로 리턴하는 문제 해결
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
Labels: fix

#134 [P0] 사용자 정보 조회 및 업데이트 기능 추가 && 인증 페이지 추가
  web/src/App.tsx
  web/src/assets/svg/LoadingImage.svg
  web/src/assets/svg/index.ts
  web/src/components/Header.tsx
  web/src/components/LoginForm.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/authlist/kakaoAuth.ts
  web/src/hooks/history.ts
  web/src/reducers/header.ts
  web/src/reducers/index.ts
  web/src/reducers/profile.ts
  web/src/reducers/survey.ts
  web/src/reducers/user.ts
  web/src/reducers/userInfo.ts
  web/src/routes/MyPages/AuthListPage.tsx
  web/src/routes/MyPages/AuthenticationPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/types/profile.ts
  web/src/types/surveyAuth.ts
  web/src/types/user.ts
  web/src/utils/UserUtils.ts
Labels: feature

#141 refactor: `SurveyService.java` 코드 리팩토링
  api/src/main/java/com/thesurvey/api/dto/request/survey/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/survey/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/survey/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/user/UserSurveyResultDto.java
  api/src/main/java/com/thesurvey/api/dto/response/user/UserSurveyTitleDto.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/exception/mapper/BadRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/mapper/ForbiddenRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/mapper/NotFoundExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/mapper/UnauthorizedRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/repository/QuestionOptionRepository.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
  api/src/test/java/com/thesurvey/api/dto/question/QuestionOptionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/question/QuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/survey/SurveyRequestDtoValidTest.java
Labels: refactor

#145 refactor: `CertificationType` enum 클래스에서 `MOBILE_PHONE`을 `IDENTITY_CARD` 대체
  api/src/main/java/com/thesurvey/api/domain/EnumTypeEntity.java
  api/src/main/java/com/thesurvey/api/domain/ParticipationId.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/converter/CertificationTypeConverter.java
Labels: refactor

#151 refactor: survey service
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionOptionMapper.java
Labels: refactor

#152 refactor: service and mapper
  api/src/main/java/com/thesurvey/api/repository/AnsweredQuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionOptionRepository.java
  api/src/main/java/com/thesurvey/api/repository/UserRepository.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
Labels: refactor

#143 feat: 설문조사 참여, 설문조사 리스트 페이지 api 연결 및 리팩토링
  docker-compose.yml
  web/src/__tests__/SurveyFormPage.test.tsx
  web/src/api/axios.ts
  web/src/api/request.ts
  web/src/components/Button/Buttons.ts
  web/src/components/Button/RectangleButton.tsx
  web/src/components/Certification.tsx
  web/src/components/CertificationIconList.tsx
  web/src/components/Header.tsx
  web/src/components/Modal/AlertModal.tsx
  web/src/components/Modal/ConfirmModal.tsx
  web/src/components/Modal/SurveyPageResultModal.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/Pagination.tsx
  web/src/components/Skeleton/Animation.ts
  web/src/components/Skeleton/SurveyListSkeleton.tsx
  web/src/components/Skeleton/SurveyPageSkeleton.tsx
  web/src/components/Styled/Animation.ts
  web/src/components/SurveyCreateForm/OptionList.tsx
  web/src/components/SurveyCreateForm/QuestionForm.tsx
  web/src/components/SurveyCreateForm/QuestionTypeSelector.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyCreateForm/SurveyDataForm.tsx
  web/src/components/SurveyListTable.tsx
  web/src/components/SurveyParticipateForm/OptionList.tsx
  web/src/components/SurveyParticipateForm/QuestionForm.tsx
  web/src/components/SurveyParticipateForm/ResponseInputForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/routes/SurveyPages/SurveyFormPage.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
  web/src/types/request/AnsweredQuestion.ts
  web/src/types/request/Question.ts
  web/src/types/request/QuestionBank.ts
  web/src/types/request/QuestionOption.ts
  web/src/types/request/Survey.ts
  web/src/types/response/QuestionBank.ts
  web/src/types/response/Survey.ts
  web/src/utils/dateFormat.ts
  web/src/utils/validate.ts
Labels: feature

#156 fix: 사용자 인증이 필요없는 설문조사 생성시 `participation` 테이블에 정보를 저장하지 않는 문제 해결
  api/src/main/java/com/thesurvey/api/domain/EnumTypeEntity.java
  api/src/main/java/com/thesurvey/api/domain/ParticipationId.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/converter/CertificationTypeConverter.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
Labels: fix

#155 feat: kakao api connecting - User authentication
  web/src/components/Header.tsx
  web/src/components/LoginForm.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/authlist/kakaoAuth.ts
  web/src/index.tsx
  web/src/reducers/header.ts
  web/src/reducers/survey.ts
  web/src/routes/MyPages/AuthListPage.tsx
  web/src/routes/MyPages/AuthenticationPage.tsx
  web/src/types/header.ts
  web/src/types/surveyAuth.ts
  web/src/utils/authService.ts
  web/src/utils/authlist/kakaoAuth.ts
  web/src/utils/authlist/naverAuth.ts
Labels: feature

#137 feat: `UserCertification` 엔티티, 기능 구현
  api/src/main/java/com/thesurvey/api/ApiApplication.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/domain/User.java
  api/src/main/java/com/thesurvey/api/domain/UserCertification.java
  api/src/main/java/com/thesurvey/api/domain/UserCertificationId.java
  api/src/main/java/com/thesurvey/api/dto/request/answeredQuestion/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/user/UserCertificationUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/DriverLicenseCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/GoogleCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/IdentityCardCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/KakaoCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/NaverCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/UserCertificationListDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/WebMailCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/repository/UserCertificationRepository.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/UserCertificationService.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserCertificationMapper.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
  api/src/test/java/com/thesurvey/api/service/UserCertificationServiceTest.java
Labels: feature

#161 fix: 병합하면서 발생한 충돌 문제 해결
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
Labels: fix

#162 feat: survey list page, survey participate page 캐시 추가 with react-query
  web/package-lock.json
  web/package.json
  web/src/api/fetchFunctions.ts
  web/src/components/ErrorPage.tsx
  web/src/components/SurveyListTable.tsx
  web/src/index.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
Labels: feature, fix

#163 refactor: 사용자 인증 정보 조회에 대한 DTO 클래스 리팩토링
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/CertificationInfo.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/DriverLicenseCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/GoogleCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/IdentityCardCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/KakaoCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/NaverCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/UserCertificationListDto.java
  api/src/main/java/com/thesurvey/api/dto/response/userCertification/WebMailCertificationInfoDto.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserCertificationMapper.java
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
Labels: refactor

#168 fix: 404 에러 발생시 처리와 설문 조사가 없을 때 처리를 분리
  web/src/components/Button/RectangleButton.tsx
  web/src/components/ErrorPage.tsx
  web/src/components/Modal/AlertModal.tsx
  web/src/components/Modal/ConfirmModal.tsx
  web/src/components/Modal/SurveyPageResultModal.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
Labels: fix

#174 fix: conflict between develop and develop-api
  api/Dockerfile
  api/src/main/java/com/thesurvey/api/dto/response/question/QuestionBankResponseDto.java
  api/src/main/java/com/thesurvey/api/repository/QuestionRepository.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/resources/application.yml
  web/Dockerfile
Labels: sync

#173 feature: 사용자 정보 조회 및 인증여부 조회 구현
  web/src/api/axios.ts
  web/src/api/request.ts
  web/src/components/Header.tsx
  web/src/components/LoginForm.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/reducers/form.ts
  web/src/routes/MyPages/AuthListPage.tsx
  web/src/routes/MyPages/AuthenticationPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/types/request/User.ts
  web/src/types/response/User.ts
  web/src/utils/UserUtils.ts
  web/src/utils/authService.ts
  web/src/utils/authlist/kakaoAuth.ts
Labels: feature, fix

#177 fix: 서버로 부터 받아오는 에러 메세지 표시, 설문 시작시간 확인 로직 수정, 인증 목록 enum 서버와 같게 수정
  web/src/__tests__/SurveyFormPage.test.tsx
  web/src/api/axios.ts
  web/src/components/Certification.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyCreateForm/SurveyDataForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
  web/src/types/labels.ts
  web/src/types/request/Survey.ts
  web/src/types/response/Survey.ts
  web/src/utils/responseErrorHandle.ts
  web/src/utils/validate.ts
Labels: fix

#176 feat: 포인트 시스템 구현
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/domain/EnumTypeEntity.java
  api/src/main/java/com/thesurvey/api/domain/PointHistory.java
  api/src/main/java/com/thesurvey/api/dto/request/answeredQuestion/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/answeredQuestion/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/answeredQuestion/AnsweredQuestionRewardPointDto.java
  api/src/main/java/com/thesurvey/api/dto/response/survey/SurveyPageDto.java
  api/src/main/java/com/thesurvey/api/dto/response/survey/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/repository/PointHistoryRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionBankRepository.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/PointHistoryService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/main/java/com/thesurvey/api/util/PointUtil.java
  api/src/main/java/com/thesurvey/api/util/StringUtil.java
  api/src/test/java/com/thesurvey/api/controller/AuthenticationControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
  api/src/test/java/com/thesurvey/api/dto/answeredQuestion/AnsweredQuestionDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/answeredQuestion/AnsweredQuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/service/AnsweredQuestionServiceTest.java
  api/src/test/java/com/thesurvey/api/service/AuthenticationServiceTest.java
  api/src/test/java/com/thesurvey/api/service/PointHistoryServiceTest.java
Labels: feature

#178 feat: 설문 참여와 생성시 isRequired 옵션 추가, 모바일뷰 수정, 획득/사용 포인트 표시
  web/src/components/CertificationIconList.tsx
  web/src/components/Modal/SurveyPageResultModal.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/Pagination.tsx
  web/src/components/SurveyCreateForm/OptionList.tsx
  web/src/components/SurveyCreateForm/QuestionForm.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyCreateForm/SurveyDataForm.tsx
  web/src/components/SurveyListTable.tsx
  web/src/components/SurveyParticipateForm/QuestionForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/components/ToggleSwitch.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
  web/src/types/request/AnsweredQuestion.ts
  web/src/types/request/Survey.ts
  web/src/types/response/QuestionBank.ts
  web/src/utils/removeEmptyAnswer.ts
  web/src/utils/responseErrorHandle.ts
Labels: feature

#180 feat: 특정 설문조사 정보 요청 시 필수 인증을 완료했는지 검사
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
Labels: revision

#182 fix: 오동작 방지를 위해 필요에 따라 버튼 비활성화
  web/src/components/Button/RectangleButton.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/utils/validate.ts
Labels: fix

#184 fix: accessibility
  web/public/logo512.png
  web/public/manifest.json
  web/src/components/CertificationIconList.tsx
  web/src/components/InputContainer.tsx
  web/src/components/LoginForm.tsx
  web/src/components/RegisterForm.tsx
  web/src/themes/darkTheme.ts
  web/src/themes/lightTheme.ts
Labels: fix

#185 feat: add timer of the survey to be started
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/utils/dateFormat.ts
Labels: feature

#187 fix: 설문 응답 검증 로직 추가, 설문 참여와 제작 페이지 테마수정
  web/src/components/Button/ImageButtons.ts
  web/src/components/Certification.tsx
  web/src/components/CertificationIconList.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/SurveyCreateForm/OptionList.tsx
  web/src/components/SurveyCreateForm/QuestionForm.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyCreateForm/SurveyDataForm.tsx
  web/src/components/SurveyParticipateForm/OptionList.tsx
  web/src/components/SurveyParticipateForm/QuestionForm.tsx
  web/src/components/SurveyParticipateForm/ResponseInputForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/routes/SurveyPages/SurveyFormPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
  web/src/themes/darkTheme.ts
  web/src/themes/lightTheme.ts
  web/src/types/styled.d.ts
  web/src/utils/removeEmptyAnswer.ts
  web/src/utils/validate.ts
Labels: fix

#190 fix: SurveyFormPage 테스트 오류나는 문제 해결
  web/src/components/Button/ImageButtons.ts
  web/src/components/Certification.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/components/SurveyCreateForm/OptionList.tsx
  web/src/components/SurveyCreateForm/QuestionForm.tsx
  web/src/components/SurveyCreateForm/SurveyDataForm.tsx
Labels: fix

#189 feat/설문 결과 리스트 조회 및 여러가지 요청사항 수정
  web/.gitignore
  web/sample.env
  web/src/__tests__/LoginPage.test.tsx
  web/src/__tests__/RegisterPage.test.tsx
  web/src/api/fetchFunctions.ts
  web/src/api/request.ts
  web/src/components/ErrorPage.tsx
  web/src/components/Header.tsx
  web/src/components/LoadingForm.tsx
  web/src/components/LoginForm.tsx
  web/src/components/SurveyResultBox.tsx
  web/src/reducers/userInfo.ts
  web/src/routes/MyPages/AuthenticationPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/types/header.ts
  web/src/types/response/AnsweredQuestion.ts
  web/src/types/response/QuestionOption.ts
  web/src/types/response/Survey.ts
  web/src/types/response/User.ts
  web/src/types/user.ts
  web/src/utils/UserUtils.ts
  web/src/utils/authService.ts
  web/src/utils/authlist/kakaoAuth.ts
Labels: feature, fix

#193 fix: 사용자 인증 만료를 검사하는 메소드에서 `@Scheduled` 어노테이션에 기준 시간대 설정
  api/src/main/java/com/thesurvey/api/service/UserCertificationService.java
Labels: fix

#191 fix: outdated survey should not be in the survey list page
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
Labels: fix

#192 build: added web ci workflow
  .github/workflows/web-ci.yml
Labels: feature

#195 fix: tone of messages
  web/src/__tests__/RegisterPage.test.tsx
  web/src/__tests__/SurveyFormPage.test.tsx
  web/src/components/ErrorPage.tsx
  web/src/components/RegisterForm.tsx
  web/src/components/SurveyCreateForm/QuestionForm.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/routes/MyPages/AuthenticationPage.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/routes/NotFound.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/utils/auth/kakaoAuth.ts
  web/src/utils/auth/naverAuth.ts
  web/src/utils/responseErrorHandle.ts
Labels: fix

#196 fix/user state in error
  web/src/components/ErrorPage.tsx
  web/src/utils/responseErrorHandle.ts
Labels: fix

#197 fix: 에러 메세지에서 중복되는 문자 삭제, 로그인 상태관리
  web/src/components/ErrorPage.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
  web/src/components/SurveyParticipateForm/SurveyParticipateForm.tsx
  web/src/reducers/header.ts
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/MyPages/SurveyResultPage.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/routes/SurveyPages/SurveyPage.tsx
  web/src/utils/responseErrorHandle.ts
Labels: fix, refactor

#198 feat: 기프티콘 구매 모달 생성(동작 안함)
  web/src/components/Button/ImageButtons.ts
  web/src/components/GifticonItem.tsx
  web/src/components/Header.tsx
  web/src/components/Modal/GifticonPurchaseModal.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/Modal/SurveyPreviewModal.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
Labels: feature
