Repository kookmin-sw/capstone-2023-40, pull requests merged in 2023-04, with the labels that each got.

#78 feat: additional validation and exception handler
  .github/workflows/gradle.yml
  api/build.gradle
  api/src/main/java/com/thesurvey/api/controller/AuthenticationController.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/domain/Survey.java
  api/src/main/java/com/thesurvey/api/domain/User.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionBankUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserLoginRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/repository/AnsweredQuestionRepository.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionOptionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
Labels: feature

#84 feat: additional validations for DTOs and integration tests for authentication
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionBankUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserLoginRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/test/java/com/thesurvey/api/controller/AuthenticationControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/BaseControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
  api/src/test/java/com/thesurvey/api/service/AuthenticationServiceTest.java
  api/src/test/java/com/thesurvey/api/service/BaseServiceTest.java
  api/src/test/java/com/thesurvey/api/service/UserServiceTest.java
Labels: feature, fix

#88 Feat: change certification icons
  web/src/assets/svg/CertificationIcons/driver-license-icon-color.svg
  web/src/assets/svg/CertificationIcons/driver-license-icon.svg
  web/src/assets/svg/CertificationIcons/google-icon-color.svg
  web/src/assets/svg/CertificationIcons/google-icon.svg
  web/src/assets/svg/CertificationIcons/idcard-icon-color.svg
  web/src/assets/svg/CertificationIcons/idcard-icon.svg
  web/src/assets/svg/CertificationIcons/kakao-icon-color.svg
  web/src/assets/svg/CertificationIcons/kakao-icon.svg
  web/src/assets/svg/CertificationIcons/mobile-phone-icon-color.svg
  web/src/assets/svg/CertificationIcons/mobile-phone-icon.svg
  web/src/assets/svg/CertificationIcons/naver-icon.svg
  web/src/assets/svg/CertificationIcons/webmail-icon-color.svg
  web/src/assets/svg/CertificationIcons/webmail-icon.svg
  web/src/assets/svg/CertificationIcons/x-icon.svg
  web/src/assets/svg/index.ts
  web/src/components/Skeleton/SurveyListSkeleton.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
Labels: feature

#90 fix: set default role of user
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/domain/User.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserResponseDto.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/test/java/com/thesurvey/api/controller/AuthenticationControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/BaseControllerTest.java
  api/src/test/java/com/thesurvey/api/service/BaseServiceTest.java
Labels: fix

#92 feat: add test code for survey
  .github/workflows/gradle.yml
  api/build.gradle
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/converter/CertificationTypeConverter.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionMapper.java
  api/src/test/java/com/thesurvey/api/SurveyTestFactory.java
  api/src/test/java/com/thesurvey/api/controller/BaseControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerIntegrateTest.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionRequestDtoValidTestValidTest.java
  api/src/test/java/com/thesurvey/api/dto/CommonTestMethod.java
  api/src/test/java/com/thesurvey/api/dto/QuestionBankUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionOptionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionOptionUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/SurveyRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/SurveyUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/repository/SurveyRepositoryTest.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature, revision, validation

#93 fix: test for survey validation
  api/src/main/java/com/thesurvey/api/dto/request/QuestionBankUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/converter/CertificationTypeConverter.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/CommonTestMethod.java
  api/src/test/java/com/thesurvey/api/dto/QuestionBankUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionOptionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionOptionUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/SurveyRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/SurveyUpdateRequestDtoValidTest.java
Labels: fix

#89 Feat: surveyform for author
  web/src/components/CertificationList.tsx
  web/src/components/SurveyForm/ChoiceAnswerForm.tsx
  web/src/components/SurveyForm/EditQuestionButton.tsx
  web/src/components/SurveyForm/QuestionTypeSelect.tsx
  web/src/components/SurveyForm/SubjectiveAnswerForm.tsx
  web/src/components/SurveyForm/SurveyDataForm.tsx
  web/src/routes/SurveyPages/SurveyFormPage.tsx
  web/src/routes/SurveyPages/SurveyListPage.tsx
  web/src/types/request/Question.ts
  web/src/types/request/Survey.ts
Labels: feature

#95 fix: put request to patch
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
Labels: revision

#97 fix: survey validation test
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/domain/AnsweredQuestion.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/AnsweredQuestionInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/AnsweredQuestionResponseDto.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/test/java/com/thesurvey/api/SurveyTestFactory.java
  api/src/test/java/com/thesurvey/api/UserTestFactory.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionBankUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionOptionUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/QuestionRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/SurveyRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/dto/SurveyUpdateRequestDtoValidTest.java
  api/src/test/java/com/thesurvey/api/repository/UserRepositoryTest.java
  api/src/test/java/com/thesurvey/api/service/AuthenticationServiceTest.java
  api/src/test/java/com/thesurvey/api/service/BaseServiceTest.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature, fix, validation

#100 feature: additional validation and Exception related to survey
  api/src/main/java/com/thesurvey/api/config/ApplicationConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SessionFilter.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/domain/QuestionBank.java
  api/src/main/java/com/thesurvey/api/exception/AuthenticationEntryPointHandler.java
  api/src/main/java/com/thesurvey/api/exception/BadRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/exception/ForbiddenRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/exception/NotFoundExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/UnauthorizedRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/repository/AnsweredQuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/ParticipationRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionOptionRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionRepository.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/ParticipationService.java
  api/src/main/java/com/thesurvey/api/service/QuestionOptionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionOptionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/test/java/com/thesurvey/api/SurveyTestFactory.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/dto/AnsweredQuestionDtoValidTest.java
  api/src/test/java/com/thesurvey/api/repository/ParticipationRepositoryTest.java
  api/src/test/java/com/thesurvey/api/repository/SurveyRepositoryTest.java
  api/src/test/java/com/thesurvey/api/repository/UserRepositoryTest.java
  api/src/test/java/com/thesurvey/api/service/QuestionServiceTest.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature, validation

#103 fix: grand revision for validation
  api/src/main/java/com/thesurvey/api/config/ApplicationConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SessionFilter.java
  api/src/main/java/com/thesurvey/api/config/SwaggerConfig.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/domain/AnsweredQuestion.java
  api/src/main/java/com/thesurvey/api/domain/AnsweredQuestionId.java
  api/src/main/java/com/thesurvey/api/domain/ParticipationId.java
  api/src/main/java/com/thesurvey/api/domain/PointHistory.java
  api/src/main/java/com/thesurvey/api/domain/Question.java
  api/src/main/java/com/thesurvey/api/domain/QuestionBank.java
  api/src/main/java/com/thesurvey/api/domain/QuestionOption.java
  api/src/main/java/com/thesurvey/api/domain/Survey.java
  api/src/main/java/com/thesurvey/api/domain/User.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserLoginRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/exception/BadRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/exception/GlobalAPIExceptionHandler.java
  api/src/main/java/com/thesurvey/api/exception/NotFoundExceptionMapper.java
  api/src/main/java/com/thesurvey/api/exception/UnauthorizedRequestExceptionMapper.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/AuthenticationService.java
  api/src/main/java/com/thesurvey/api/service/ParticipationService.java
  api/src/main/java/com/thesurvey/api/service/QuestionOptionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/java/com/thesurvey/api/util/UserUtil.java
  api/src/test/java/com/thesurvey/api/SurveyTestFactory.java
  api/src/test/java/com/thesurvey/api/UserTestFactory.java
  api/src/test/java/com/thesurvey/api/controller/AuthenticationControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/BaseControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/repository/ParticipationRepositoryTest.java
  api/src/test/java/com/thesurvey/api/repository/SurveyRepositoryTest.java
  api/src/test/java/com/thesurvey/api/repository/UserRepositoryTest.java
  api/src/test/java/com/thesurvey/api/service/AuthenticationServiceTest.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: fix, revision, validation

#105 feat: add StringUtil.java
  api/src/main/java/com/thesurvey/api/service/QuestionOptionService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionOptionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/UserMapper.java
  api/src/main/java/com/thesurvey/api/util/StringUtil.java
  api/src/main/java/com/thesurvey/api/util/UserUtil.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature

#108 feat: revise test code for survey service and controller
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature

#106 feat: state management during user's login and register logic & minor updates on modal
  web/.eslintrc.js
  web/package-lock.json
  web/package.json
  web/src/__tests__/MainPage.test.tsx
  web/src/components/Header.tsx
  web/src/components/Modal/AlertModal.tsx
  web/src/components/Modal/HeaderModal.tsx
  web/src/components/RegisterForm.tsx
  web/src/hooks/history.ts
  web/src/hooks/useOnClickOutside.ts
  web/src/index.tsx
  web/src/reducers/auth.ts
  web/src/reducers/form.ts
  web/src/reducers/header.ts
  web/src/reducers/index.ts
  web/src/reducers/store.ts
  web/src/reducers/userInfo.ts
  web/src/routes/LoginPage.tsx
  web/src/routes/MainPage.tsx
  web/src/routes/MyPages/AuthListPage.tsx
  web/src/routes/MyPages/ProfilePage.tsx
  web/src/routes/SurveyPages/SurveyLoginRequiredPage.tsx
  web/src/types/userInfo.ts
Labels: feature

#113 fix: follow api docs
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/resources/application-dev.yml
Labels: documentation, fix

#115 feat: pagination for survey list
  api/src/main/java/com/thesurvey/api/config/SwaggerConfig.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/dto/request/PageableSwagger.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyListPageDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyPageDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/service/SurveyServiceTest.java
Labels: feature

#119 feat: swagger migration from spring-fox to spring-doc
  api/build.gradle
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
  api/src/main/java/com/thesurvey/api/config/SessionFilter.java
  api/src/main/java/com/thesurvey/api/config/SwaggerConfig.java
  api/src/main/java/com/thesurvey/api/controller/AuthenticationController.java
  api/src/main/java/com/thesurvey/api/controller/CustomController.java
  api/src/main/java/com/thesurvey/api/controller/SurveyController.java
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/PageableSwagger.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionBankUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionOptionUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/QuestionRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserLoginRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserRegisterRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/UserUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/AnsweredQuestionInfoDto.java
  api/src/main/java/com/thesurvey/api/dto/response/AnsweredQuestionResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionBankResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionOptionResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyListPageDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyPageDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserResponseDto.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/main/resources/application-dev.yml
Labels: documentation, revision

#123 fix: datetime precision
  api/src/main/java/com/thesurvey/api/domain/BaseTimeEntity.java
  api/src/main/java/com/thesurvey/api/domain/Participation.java
  api/src/main/java/com/thesurvey/api/domain/PointHistory.java
  api/src/main/java/com/thesurvey/api/domain/PointHistoryId.java
  api/src/main/java/com/thesurvey/api/domain/Survey.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/request/SurveyUpdateRequestDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionBankResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyPageDto.java
  api/src/main/java/com/thesurvey/api/dto/response/SurveyResponseDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserResponseDto.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
Labels: fix

#124 fix: allowed origin
  api/src/main/java/com/thesurvey/api/config/SecurityConfiguration.java
Labels: fix

#125 Feat: add animation on skeleton ui
  web/src/components/Skeleton/SurveyListSkeleton.tsx
  web/src/components/Skeleton/SurveyPageSkeleton.tsx
  web/src/components/Styled/Animation.ts
  web/src/routes/SurveyPages/SurveyListPage.tsx
Labels: feature

#126 feat: Add API to retrieve results of user-created survey
  api/src/main/java/com/thesurvey/api/controller/UserController.java
  api/src/main/java/com/thesurvey/api/domain/AnsweredQuestion.java
  api/src/main/java/com/thesurvey/api/domain/EnumTypeEntity.java
  api/src/main/java/com/thesurvey/api/dto/request/AnsweredQuestionDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionBankAnswerDto.java
  api/src/main/java/com/thesurvey/api/dto/response/QuestionOptionAnswerDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserSurveyResultDto.java
  api/src/main/java/com/thesurvey/api/dto/response/UserSurveyTitleDto.java
  api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
  api/src/main/java/com/thesurvey/api/repository/AnsweredQuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionOptionRepository.java
  api/src/main/java/com/thesurvey/api/repository/QuestionRepository.java
  api/src/main/java/com/thesurvey/api/repository/SurveyRepository.java
  api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionOptionService.java
  api/src/main/java/com/thesurvey/api/service/QuestionService.java
  api/src/main/java/com/thesurvey/api/service/SurveyService.java
  api/src/main/java/com/thesurvey/api/service/UserService.java
  api/src/main/java/com/thesurvey/api/service/mapper/AnsweredQuestionMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/QuestionBankMapper.java
  api/src/main/java/com/thesurvey/api/service/mapper/SurveyMapper.java
  api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
  api/src/test/java/com/thesurvey/api/controller/UserControllerTest.java
Labels: feature
